name: Build
on:
  push:
    branches:
      - v1
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install and build
        run: |
          pnpm install
          pnpm build

      - name: Test
        run: |
          pnpm test run
